### PR TITLE
Added Enduring CSS by Ben Frain to Longer Readings

### PR DESCRIPTION
**Pull request by DanGamble89**
Not sure how you feel about having books on here as I can't see any others but Ben has released a book recently that is aimed at tackling this problem.

### CODE REVIEW

**Comment by davidtheclark** [comment]
I'm all for promoting Ben's work, but this list is focused on things that people can quickly access online.

**Comment by DanGamble89** [comment]
That's fair. I think he wrote an article on it that outlays the principles. Would a PR with that be more along the right lines?

**Comment by davidtheclark** [comment]
Yep that'd be great. I remember liking that article.

**Comment by DanGamble89** [comment]
Scrap that, probably helps if i have a thorough read of the list. It's already in there :)

**Pull request closed without merging**
